// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalHealthTracker.Data.Context;

namespace PersonalHealthTracker.Data.Migrations
{
    [DbContext(typeof(PersonalHealthTrackerDbContext))]
    [Migration("20190512042552_add-physicalActivity-physicalActivityType-relationship")]
    partial class addphysicalActivityphysicalActivityTyperelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalHealthTracker.Domain.Model.Physical_Activity_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Physical_Activity_Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Jogging"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Walking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Swimming"
                        });
                });

            modelBuilder.Entity("PersonalHealthTracker.Domain.Models.Physical_Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaloriesBurned");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Duration");

                    b.Property<int>("Physical_Activity_TypeId");

                    b.Property<int>("dayOfWeek");

                    b.HasKey("Id");

                    b.HasIndex("Physical_Activity_TypeId");

                    b.ToTable("Physical_Activities");
                });

            modelBuilder.Entity("PersonalHealthTracker.Domain.Models.Physical_Activity", b =>
                {
                    b.HasOne("PersonalHealthTracker.Domain.Model.Physical_Activity_Type", "Physical_Activity_Type")
                        .WithMany()
                        .HasForeignKey("Physical_Activity_TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
